In [1]:
# I found a name 'wld' in the data, 
# I assume it indicates the total trading amount of the world and try to figure out if it's correct

In [2]:
import pandas as pd

In [3]:
df_1962 = pd.read_csv('D:\Data\Data from OEC\SITC_1962.csv',header = None)

In [5]:
df_1962.columns = ['year', 'ori', 'des', 'SITC', 'exp_v', 'imp_v']

In [6]:
df_1962.head()

   year  ori  des  SITC   exp_v   imp_v
0  1962  afg  aus  6412     0.0  3000.0
1  1962  afg  aus  6590  4000.0     0.0
2  1962  afg  aus  6658     0.0  4000.0
3  1962  afg  aus  6991     0.0  9000.0
4  1962  afg  aus  8510     0.0  1000.0

In [7]:
# use afg as exporter to do the test

In [8]:
df_afg = df_1962[df_1962['ori'] == 'afg']

In [9]:
df_afg

      year  ori  des  SITC     exp_v       imp_v
0     1962  afg  aus  6412       0.0      3000.0
1     1962  afg  aus  6590    4000.0         0.0
2     1962  afg  aus  6658       0.0      4000.0
3     1962  afg  aus  6991       0.0      9000.0
4     1962  afg  aus  8510       0.0      1000.0
5     1962  afg  aus  8950       0.0      2000.0
6     1962  afg  aus  9310       0.0      2000.0
7     1962  afg  aut  2919   16000.0         0.0
8     1962  afg  aut  5540       0.0      5000.0
9     1962  afg  aut  6544       0.0     25000.0
10    1962  afg  aut  6590   44000.0         0.0
11    1962  afg  aut  6610       0.0      2000.0
12    1962  afg  aut  6930       0.0      5000.0
13    1962  afg  aut  6940       0.0      1000.0
14    1962  afg  aut  8510       0.0      1000.0
15    1962  afg  aut  9310       0.0      1000.0
16    1962  afg  bel  2681    9000.0         0.0
17    1962  afg  bel  5410       0.0      1000.0
18    1962  afg  bel  6592    9000.0         0.0
19    1962  afg  bel  6643       0.0      4000.0
20    1962  afg  bel  6658       0.0      2000.0
21    1962  afg  bel  6730       0.0      9000.0
22    1962  afg  bel  6780       0.0     12000.0
23    1962  afg  bel  6940       0.0     41000.0
24    1962  afg  bel  7131    1000.0         0.0
25    1962  afg  bel  7782       0.0     15000.0
26    1962  afg  bel  7928       0.0      2000.0
27    1962  afg  bgr  2110    8000.0         0.0
28    1962  afg  bgr  2114   11000.0         0.0
29    1962  afg  bgr  2120    3000.0         0.0
...    ...  ...  ...   ...       ...         ...
1343  1962  afg  wld  8720       0.0     66000.0
1344  1962  afg  wld  8740       0.0     23000.0
1345  1962  afg  wld  8745    1000.0    214000.0
1346  1962  afg  wld  8821       0.0      9000.0
1347  1962  afg  wld  8822       0.0     45000.0
1348  1962  afg  wld  8830  111000.0     44000.0
1349  1962  afg  wld  8850       0.0    298000.0
1350  1962  afg  wld  8921       0.0     10000.0
1351  1962  afg  wld  8942       0.0      9000.0
1352  1962  afg  wld  8946       0.0     23000.0
1353  1962  afg  wld  8947    2000.0      3000.0
1354  1962  afg  wld  8950       0.0    202000.0
1355  1962  afg  wld  8952       0.0     53000.0
1356  1962  afg  wld  8960    1000.0         0.0
1357  1962  afg  wld  8972       0.0     23000.0
1358  1962  afg  wld  8973       0.0      5000.0
1359  1962  afg  wld  8980       0.0      4000.0
1360  1962  afg  wld  8983       0.0      8000.0
1361  1962  afg  wld  8990    2000.0      2000.0
1362  1962  afg  wld  8993       0.0    382000.0
1363  1962  afg  wld  8994       0.0      2000.0
1364  1962  afg  wld  8997       0.0      4000.0
1365  1962  afg  wld  8999       0.0      2000.0
1366  1962  afg  wld  9110    1000.0         0.0
1367  1962  afg  wld  9310  181000.0  73131000.0
1368  1962  afg  wld  9410    1000.0         0.0
1369  1962  afg  xxh   570    2000.0         0.0
1370  1962  afg  xxh  2919    5000.0         0.0
1371  1962  afg  xxh  3345       0.0      2000.0
1372  1962  afg  yug  5239       0.0      1000.0

[1373 rows x 6 columns]

In [10]:
# since a big number appears, we use SITC 9310 to test

In [11]:
df_afg_9310 = df_afg[df_afg['SITC'] == 9310 ]

In [12]:
df_afg_9310

      year  ori  des  SITC     exp_v       imp_v
6     1962  afg  aus  9310       0.0      2000.0
15    1962  afg  aut  9310       0.0      1000.0
73    1962  afg  che  9310       0.0     17000.0
83    1962  afg  chn  9310       0.0      1000.0
122   1962  afg  csk  9310   32000.0   5467000.0
242   1962  afg  deu  9310   40000.0     95000.0
379   1962  afg  fdr  9310   40000.0     95000.0
492   1962  afg  gbr  9310       0.0     67000.0
514   1962  afg  hkg  9310       0.0     10000.0
625   1962  afg  ind  9310    8000.0     66000.0
680   1962  afg  irn  9310    1000.0    121000.0
731   1962  afg  ita  9310       0.0      2000.0
811   1962  afg  jpn  9310       0.0    121000.0
859   1962  afg  lbn  9310       0.0      7000.0
892   1962  afg  nld  9310       0.0      3000.0
957   1962  afg  pol  9310       0.0    453000.0
1035  1962  afg  sun  9310   98000.0  65799000.0
1044  1962  afg  swe  9310       0.0      2000.0
1049  1962  afg  tha  9310    2000.0         0.0
1140  1962  afg  usa  9310       0.0    897000.0
1367  1962  afg  wld  9310  181000.0  73131000.0

In [13]:
#if wld means the total trading value of the world, then the sum of the rest should equals to the last one

In [14]:
df_rest = df_afg_9310[df_afg_9310['des'] != 'wld' ]

In [15]:
df_rest['imp_v'].sum()

73226000.0

In [16]:
df_rest['exp_v'].sum()

221000.0

In [17]:
#the sum is greater than the value of 'wld', but the diffirecen is not too big